### ISSUE TITLE
buton tıklanma event ı çalışmıyor 

### ISSUE THREAD

**Issue by ozcan00** [ozcan00/xamarin#1]
Ben kullanıcı adı ve şifre yi girip login dediğimde uygulama kasıp bekliyor ve kapanıyor
bir de bu alanda yeni olduğum için bir türlü butona tıklayınca yeni bir sayfaya geçiş yapamadım

**Comment by omersezer** [comment]
Login butnuna tıklama işleminde recursive bir fonksiyon oluşturmuşsun. Bu fonksiyondan hiç bir zaman çıkamayacağı için aslında sonsuz bir döngüye giriyor. Bu yüzden bekleyip kapanıyor.
